name: Run Artisan After Deploy

on:
  push:
    branches:
      - main  # palitan kung ibang branch ginagamit mo

jobs:
  run-artisan:
    runs-on: ubuntu-latest
    steps:
      - name: Call Laravel Artisan Route
        run: |
          curl --silent https://dsa-app-production-205e.up.railway.app/run-artisan?key=supersecretkey123
 